version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      # Mount the source code for hot reloading
      - .:/app
      # Exclude node_modules from volume mounting
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # Add this to ensure Next.js accepts connections from Docker
      - NEXT_PUBLIC_HOST=0.0.0.0
    # Keep the container running
    stdin_open: true
    tty: true 