FROM node:22.14 

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm && \
    npm install

COPY public public
COPY src src
COPY tailwind.config.js tailwind.config.js
COPY tsconfig.json tsconfig.json

EXPOSE 3000

CMD ["npm", "start"]